/**
 * Created by Bartek on 2015-01-09.
 */
var CELL_FULL_WIDTH;
var CELL_HALF_OPEN_WIDTH;
var CELL_OPEN_WIDTH;

var CELL_FULL_HEIGHT;
var CELL_HALF_OPEN_HEIGHT;
var CELL_OPEN_HEIGHT;

var GUTTER = 0.05;

var HORIZONTAL_RATIO = 2.37037;
var VERTICAL_RATIO = 0.421875;

function onGridLoad(){

    CELL_FULL_WIDTH = window.innerWidth * 0.96 /12;
    CELL_HALF_OPEN_WIDTH = CELL_FULL_WIDTH - (CELL_FULL_WIDTH) * GUTTER;
    CELL_OPEN_WIDTH = CELL_HALF_OPEN_WIDTH - (CELL_FULL_WIDTH) * GUTTER;

    CELL_FULL_HEIGHT = window.innerHeight * 0.96 /16;
    CELL_HALF_OPEN_HEIGHT = CELL_FULL_HEIGHT - (CELL_FULL_HEIGHT) * GUTTER;
    CELL_OPEN_HEIGHT = CELL_HALF_OPEN_HEIGHT - (CELL_FULL_HEIGHT) * GUTTER;

}


onGridLoad(); //initial load
